name: Parse Gmail Emails Daily

on:
  schedule:
    # Run every morning at 6:00 AM UTC (1:00 PM +07)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  parse-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Set environment variables for GitHub Secrets
      run: |
        echo "USE_GITHUB_SECRETS=true" >> $GITHUB_ENV
        echo "GOOGLE_CREDENTIALS_JSON=${{ secrets.GOOGLE_CREDENTIALS_JSON }}" >> $GITHUB_ENV
        echo "GOOGLE_TOKEN_JSON=${{ secrets.GOOGLE_TOKEN_JSON }}" >> $GITHUB_ENV
        echo "DATA_FOLDER=$GITHUB_WORKSPACE/data" >> $GITHUB_ENV
        
    - name: Run email parser
      run: python scholar_alters/parse_gmail_message.py
        
    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain data/)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Auto-update: Parse emails $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
        git push
