name: Parse Gmail Emails Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  parse-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Set environment variables for GitHub Secrets
      run: |
        echo "USE_GITHUB_SECRETS=true" >> $GITHUB_ENV
        echo "DATA_FOLDER=$GITHUB_WORKSPACE/data" >> $GITHUB_ENV
        
    - name: Validate and set up JSON secrets
      run: |
        # Validate and create token.json
        if [ -n "${{ secrets.GOOGLE_TOKEN_JSON }}" ]; then
          echo "${{ secrets.GOOGLE_TOKEN_JSON }}" > token_temp.json
          if python -c "import json; json.load(open('token_temp.json'))"; then
            echo "GOOGLE_TOKEN_JSON is valid JSON"
            mv token_temp.json data/token.json
          else
            echo "GOOGLE_TOKEN_JSON is invalid JSON"
            exit 1
          fi
        else
          echo "GOOGLE_TOKEN_JSON secret is not set"
          exit 1
        fi

        # Validate and create credentials.json
        if [ -n "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" ]; then
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials_temp.json
          if python -c "import json; json.load(open('credentials_temp.json'))"; then
            echo "GOOGLE_CREDENTIALS_JSON is valid JSON"
            mv credentials_temp.json data/credentials.json
          else
            echo "GOOGLE_CREDENTIALS_JSON is invalid JSON"
            exit 1
          fi
        else
          echo "GOOGLE_CREDENTIALS_JSON secret is not set"
          exit 1
        fi
        
    - name: Run email parser
      run: python -m scholar_alters.parse_gmail_message
        
    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain data/)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git commit -m "Auto-update: Parse emails $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
        git push
